[project]
name = "avito-ds-bootcamp"
version = "0.1.0"
description = "Тестовое задание на Avito DS BootCamp"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catboost>=1.2.10",
    "lightgbm>=4.7.0",
    "numpy>=2.5.3",
    "optuna>=5.0.0",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "xgboost>=3.4.1",
]
